import os
from pathlib import Path

from openai import BadRequestError, OpenAI
from dotenv import load_dotenv


ENV_DIR = Path(__file__).resolve().parent.parent / "env"

# Keep explicitly exported variables authoritative, while supporting the
# environment-file layout generated by the Teams project template.
load_dotenv(ENV_DIR / ".env.local", override=False)
load_dotenv(ENV_DIR / ".env", override=False)


AZURE_OPENAI_API_KEY = os.getenv(
    "AZURE_OPENAI_API_KEY",
    ""
)

AZURE_OPENAI_ENDPOINT = os.getenv(
    "AZURE_OPENAI_ENDPOINT",
    ""
)

AZURE_OPENAI_DEPLOYMENT = os.getenv(
    "AZURE_OPENAI_DEPLOYMENT",
    os.getenv("AZURE_OPENAI_DEPLOYMENT_NAME", ""),
)

LLM_PROVIDER = os.getenv("LLM_PROVIDER", "azure").strip().lower()
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-3.1-flash-lite")


def _get_client() -> OpenAI:

    if (
        not AZURE_OPENAI_API_KEY
        or AZURE_OPENAI_API_KEY.startswith("your-")
    ):
        raise RuntimeError(
            "Set a real AZURE_OPENAI_API_KEY in Taxpal/env/.env.local."
        )

    if (
        not AZURE_OPENAI_ENDPOINT
        or "your-resource-name" in AZURE_OPENAI_ENDPOINT
    ):
        raise RuntimeError(
            "Set a real AZURE_OPENAI_ENDPOINT in Taxpal/env/.env.local."
        )

    if (
        not AZURE_OPENAI_DEPLOYMENT
        or AZURE_OPENAI_DEPLOYMENT.startswith("your-")
    ):
        raise RuntimeError(
            "AZURE_OPENAI_DEPLOYMENT_NAME is not configured."
        )

    base_url = (
        AZURE_OPENAI_ENDPOINT.rstrip("/")
        + "/openai/v1/"
    )

    return OpenAI(
        api_key=AZURE_OPENAI_API_KEY,
        base_url=base_url,
    )


SYSTEM_PROMPT = """You are TaxPal, a warm, practical Ugandan tax assistant.
RULES:
1. Answer ONLY using the context provided below. Do not use knowledge from outside the context.
2. Sound like a knowledgeable person helping a colleague, not a legal document or customer-service script. Use contractions and ordinary Ugandan business language where natural, while remaining professional.
3. Begin with the useful answer—not with phrases such as "Certainly", "According to the provided context", or a restatement of the question.
4. Prefer two or three short paragraphs. Use bullets only for genuine lists, steps, rates, or comparisons. Explain technical terms in everyday language and use a brief example when it would make the answer clearer.
5. Cite supporting context internally with [S1], [S2], and so on after relevant factual claims. These markers are removed before display, so never explain them or refer to them as source numbers.
6. Do not recite section numbers or formal legal references unless the user asks for the legal provision. Mention URA or a document naturally only when it adds value.
7. If a later Amendment Act conflicts with a base act, use the amendment and explain the change plainly.
8. If the context is incomplete, be transparent about the specific gap and suggest the most useful next step. Avoid generic refusal language when a partial helpful answer is possible.
9. Never make up facts, section numbers, clause references, or legal provisions.
10. Ask at most one natural follow-up question, and only when the answer genuinely depends on missing details. Do not end every response with a question.
11. Add a brief advice disclaimer only when the user is making a consequential filing, payment, compliance, or business decision. Do not attach a disclaimer to simple definitions or general explanations.
"""


def _generate_with_gemini(
    prompt: str,
    system_instruction: str = SYSTEM_PROMPT,
) -> str:
    if not GEMINI_API_KEY or GEMINI_API_KEY.startswith("your-"):
        raise RuntimeError(
            "Set a real GEMINI_API_KEY in Taxpal/env/.env.local."
        )

    from google import genai
    from google.genai import types

    client = genai.Client(api_key=GEMINI_API_KEY)
    response = client.models.generate_content(
        model=GEMINI_MODEL,
        contents=prompt,
        config=types.GenerateContentConfig(
            system_instruction=system_instruction,
            temperature=0.1,
        ),
    )
    return response.text or "I could not generate an answer."


def _generate_with_azure(
    prompt: str,
    system_instruction: str = SYSTEM_PROMPT,
) -> str:
    client = _get_client()
    try:
        response = client.chat.completions.create(
            model=AZURE_OPENAI_DEPLOYMENT,
            messages=[
                {"role": "system", "content": system_instruction},
                {"role": "user", "content": prompt},
            ],
            temperature=0.1,
        )
        return response.choices[0].message.content or "I could not generate an answer."
    except BadRequestError as exc:
        if "unsupported" not in str(exc).lower():
            raise
        response = client.responses.create(
            model=AZURE_OPENAI_DEPLOYMENT,
            instructions=system_instruction,
            input=prompt,
        )
        return response.output_text or "I could not generate an answer."


def _generate_text(
    prompt: str,
    system_instruction: str = SYSTEM_PROMPT,
) -> str:
    if LLM_PROVIDER == "gemini":
        return _generate_with_gemini(prompt, system_instruction)
    if LLM_PROVIDER == "azure":
        return _generate_with_azure(prompt, system_instruction)

    raise RuntimeError(
        f"Unsupported LLM_PROVIDER '{LLM_PROVIDER}'. Use 'gemini' or 'azure'."
    )


def _format_history(history: list[dict] | None) -> str:
    if not history:
        return "No previous conversation."

    lines = []
    for message in history[-8:]:
        role = str(message.get("role", "user")).upper()
        content = str(message.get("content", "")).strip()
        if content:
            lines.append(f"{role}: {content}")
    return "\n".join(lines) or "No previous conversation."


def rewrite_question_for_retrieval(
    question: str,
    history: list[dict] | None = None,
) -> str:
    """Turn a context-dependent follow-up into a standalone search query."""
    if not history:
        return question.strip()

    prompt = (
        f"CONVERSATION:\n{_format_history(history)}\n\n"
        f"NEW USER MESSAGE:\n{question.strip()}\n\n"
        "Return only one concise, standalone tax-law search question. "
        "Resolve pronouns such as 'that' or 'it' using the conversation."
    )
    rewritten = _generate_text(
        prompt,
        system_instruction=(
            "Rewrite follow-up questions for a Ugandan tax-law retrieval "
            "system. Do not answer the question and do not add commentary."
        ),
    )
    return rewritten.strip().strip('"') or question.strip()


def answer_tax_question(
    question: str,
    documents: list[dict],
    history: list[dict] | None = None,
    user_profile: dict[str, str] | None = None,
) -> str:
    """
    Generate an answer grounded in retrieved tax-law documents.
    """

    if not documents:
        return (
            "I could not find enough information in the "
            "available Ugandan tax-law documents to answer "
            "that reliably."
        )

    context_parts = []

    for index, document in enumerate(
        documents,
        start=1,
    ):

        text = document.get("text", "")
        metadata = document.get(
            "metadata",
            {}
        )

        title = metadata.get(
            "title",
            "Unknown document"
        )

        section = metadata.get(
            "section",
            ""
        )

        source = metadata.get("source", "")
        url = metadata.get("url", "")
        evidence_type = metadata.get("evidence_type", "local_document")

        context_parts.append(
            f"""
SOURCE [S{index}]
Document: {title}
Section: {section}
Source: {source}
URL: {url}
Evidence type: {evidence_type}

{text}
"""
        )

    context = "\n".join(
        context_parts
    )

    from user_memory import profile_context

    prompt = (
        f"RECENT CONVERSATION:\n{_format_history(history)}\n\n"
        f"CONSENTED USER PROFILE:\n{profile_context(user_profile)}\n\n"
        f"CURRENT QUESTION:\n{question}\n\n"
        f"TAX-LAW CONTEXT:\n{context}"
    )
    return _generate_text(prompt)
