import os
from pathlib import Path

from openai import OpenAI
from dotenv import load_dotenv


ENV_DIR = Path(__file__).resolve().parent.parent / "env"

# Keep explicitly exported variables authoritative, while supporting the
# environment-file layout generated by the Teams project template.
load_dotenv(ENV_DIR / ".env.local", override=False)
load_dotenv(ENV_DIR / ".env", override=False)


AZURE_OPENAI_API_KEY = os.getenv(
    "AZURE_OPENAI_API_KEY",
    ""
)

AZURE_OPENAI_ENDPOINT = os.getenv(
    "AZURE_OPENAI_ENDPOINT",
    ""
)

AZURE_OPENAI_DEPLOYMENT = os.getenv(
    "AZURE_OPENAI_DEPLOYMENT",
    os.getenv("AZURE_OPENAI_DEPLOYMENT_NAME", ""),
)

LLM_PROVIDER = os.getenv("LLM_PROVIDER", "azure").strip().lower()
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-3.1-flash-lite")


def _get_client() -> OpenAI:

    if (
        not AZURE_OPENAI_API_KEY
        or AZURE_OPENAI_API_KEY.startswith("your-")
    ):
        raise RuntimeError(
            "Set a real AZURE_OPENAI_API_KEY in Taxpal/env/.env.local."
        )

    if (
        not AZURE_OPENAI_ENDPOINT
        or "your-resource-name" in AZURE_OPENAI_ENDPOINT
    ):
        raise RuntimeError(
            "Set a real AZURE_OPENAI_ENDPOINT in Taxpal/env/.env.local."
        )

    if (
        not AZURE_OPENAI_DEPLOYMENT
        or AZURE_OPENAI_DEPLOYMENT.startswith("your-")
    ):
        raise RuntimeError(
            "AZURE_OPENAI_DEPLOYMENT_NAME is not configured."
        )

    base_url = (
        AZURE_OPENAI_ENDPOINT.rstrip("/")
        + "/openai/v1/"
    )

    return OpenAI(
        api_key=AZURE_OPENAI_API_KEY,
        base_url=base_url,
    )


SYSTEM_PROMPT = (
    "You are TaxPal, an assistant for Ugandan taxation. "
    "Answer using only the tax-law context provided to you. "
    "Do not invent tax rates, laws, sections, deadlines, exemptions, "
    "or obligations. If the context is insufficient, say so. "
    "When possible, mention the document title and section supporting "
    "the answer. This is general information and not professional tax "
    "or legal advice."
)


def _answer_with_gemini(prompt: str) -> str:
    if not GEMINI_API_KEY or GEMINI_API_KEY.startswith("your-"):
        raise RuntimeError(
            "Set a real GEMINI_API_KEY in Taxpal/env/.env.local."
        )

    from google import genai
    from google.genai import types

    client = genai.Client(api_key=GEMINI_API_KEY)
    response = client.models.generate_content(
        model=GEMINI_MODEL,
        contents=prompt,
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_PROMPT,
            temperature=0.1,
        ),
    )
    return response.text or "I could not generate an answer."


def _answer_with_azure(prompt: str) -> str:
    client = _get_client()
    response = client.chat.completions.create(
        model=AZURE_OPENAI_DEPLOYMENT,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": prompt},
        ],
        temperature=0.1,
    )
    return response.choices[0].message.content or "I could not generate an answer."


def answer_tax_question(
    question: str,
    documents: list[dict],
) -> str:
    """
    Generate an answer grounded in retrieved tax-law documents.
    """

    if not documents:
        return (
            "I could not find enough information in the "
            "available Ugandan tax-law documents to answer "
            "that reliably."
        )

    context_parts = []

    for index, document in enumerate(
        documents,
        start=1,
    ):

        text = document.get("text", "")
        metadata = document.get(
            "metadata",
            {}
        )

        title = metadata.get(
            "title",
            "Unknown document"
        )

        section = metadata.get(
            "section",
            ""
        )

        context_parts.append(
            f"""
SOURCE {index}
Document: {title}
Section: {section}

{text}
"""
        )

    context = "\n".join(
        context_parts
    )

    prompt = (
        f"QUESTION:\n{question}\n\n"
        f"TAX-LAW CONTEXT:\n{context}"
    )

    if LLM_PROVIDER == "gemini":
        return _answer_with_gemini(prompt)
    if LLM_PROVIDER == "azure":
        return _answer_with_azure(prompt)

    raise RuntimeError(
        f"Unsupported LLM_PROVIDER '{LLM_PROVIDER}'. Use 'gemini' or 'azure'."
    )
