FROM python:3.12-slim

WORKDIR /app

ENV HF_HOME=/root/.cache/huggingface

COPY src/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

COPY src/ /app/

CMD ["uvicorn", "tax_search_api:app", "--host", "0.0.0.0", "--port", "8001"]
